[book]
authors = ["James Munns"]
multilingual = false
src = "src"
title = "The Embedded Rust Book"

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[output.html]
git-repository-url = "https://github.com/rust-embedded/book"
