[book]
authors = ["James Munns"]
src = "src"
title = "The Embedded Rust Book"

[output.html]
git-repository-url = "https://github.com/rust-embedded/book"
additional-css = [
  "theme/css/switcher.css",
]
additional-js = [
  "theme/js/switcher.js",
]

[preprocessor.gettext]
optional = true
after = ["links"]
