#import "../config.typ": *

#h1((en: [Design Contracts],
  de: [Design-Verträge],
  ja: [設計契約],
  zh: [设计约定(design contracts)],
), offset: whole)

#tr((
en: [
  In our last chapter, we wrote an interface that _didn't_ enforce
  design contracts. Let's take another look at our imaginary GPIO
  configuration register:
],
de: [
  Im letzten Kapitel haben wir eine Schnittstelle geschrieben, die
  _keine_ Design-Verträge (Design Contracts) durchsetzte. Werfen wir
  noch einmal einen Blick auf unser fiktives GPIO-Konfigurationsregister:
],
ja: [
  前回、設計契約を強制_しない_インタフェースを書きました。架空のGPIO設定レジスタをもう一度見てみましょう。
],
zh: [
  在我们的上个章节中，我们写了一个接口，但没有强制遵守设计约定。让我们再看下我们假想的GPIO配置寄存器：
]))

#include "gpio-table.typ"

#tr((
en: [
  If we instead checked the state before making use of the underlying
  hardware, enforcing our design contracts at runtime, we might write code
  that looks like this instead:
],
de: [
  Wenn wir stattdessen den Zustand überprüfen würden, bevor wir die
  zugrundeliegende Hardware nutzen, und dabei unsere Entwurfsverträge zur
  Laufzeit durchsetzen würden, könnten wir stattdessen Code schreiben, der
  wie folgt aussieht:
],
ja: [
  ハードウェアを使う前に状態をチェックし、実行時に設計契約を強制すると、コードは次のように書くことができます。

],
zh: [
  如果在使用底层硬件之前检查硬件的状态，在运行时强制用户遵守设计约定，代码可能像这一样:
]))

#raw(block: true, lang: "rust",
"/// " + ts((
    en: "GPIO interface",
    de: "GPIO-Schnittstelle",
    ja: "GPIOインタフェース",
    zh: "GPIO接口",
  )) + "
struct GpioConfig {
    /// " + ts((
        en: "GPIO Configuration structure generated by svd2rust",
        de: "Von svd2rust generierte GPIO-Konfigurationsstruktur",
        ja: "svd2rustによって生成されたGPIO設定構造体",
        zh: "由svd2rust生成的GPIO配制结构体"
      )) + "
    periph: GPIO_CONFIG,
}

impl GpioConfig {
    pub fn set_enable(&mut self, is_enabled: bool) {
        self.periph.modify(|_r, w| {
            w.enable().set_bit(is_enabled)
        });
    }

    pub fn set_direction(&mut self, is_output: bool) -> Result<(), ()> {
        if self.periph.read().enable().bit_is_clear() {
            // " + ts((
                en: "Must be enabled to set direction",
                de: "Muss aktiviert sein, um die Richtung festzulegen.",
                ja: "方向を設定するには、有効化されてなければなりません",
                zh: "必须被使能配置方向"
              )) + "
            return Err(());
        }

        self.periph.modify(|r, w| {
            w.direction().set_bit(is_output)
        });

        Ok(())
    }

    pub fn set_input_mode(&mut self, variant: InputMode) -> Result<(), ()> {
        if self.periph.read().enable().bit_is_clear() {
            // " + ts((
                en: "Must be enabled to set input mode",
                de: "Muss aktiviert sein, um den Eingabemodus festzulegen.",
                ja: "入力モードを設定するには、有効化されてなければなりません",
                zh: "必须被使能配置输入模式",
              )) + "
            return Err(());
        }

        if self.periph.read().direction().bit_is_set() {
            // " + ts((
                en: "Direction must be input",
                de: "Die Richtung muss input sein.",
                ja: "方向は入力でなければなりません",
                zh: "方向必须被设置成输入",
              )) + "
            return Err(());
        }

        self.periph.modify(|_r, w| {
            w.input_mode().variant(variant)
        });

        Ok(())
    }

    pub fn set_output_status(&mut self, is_high: bool) -> Result<(), ()> {
        if self.periph.read().enable().bit_is_clear() {
            // " + ts((
                en: "Must be enabled to set output status",
                de: "Muss aktiviert sein, um den Ausgangsstatus festzulegen.",
                ja: "方向は入力でなければなりません",
                zh: "设置输出状态必须被使能",
              )) + "
            return Err(());
        }

        if self.periph.read().direction().bit_is_clear() {
            // " + ts((
                en: "Direction must be output",
                de: "Die Richtung muss output sein.",
                ja: "方向は出力でなければなりません",
                zh: "方向必须是输出",
              )) + "
            return Err(());
        }

        self.periph.modify(|_r, w| {
            w.output_mode.set_bit(is_high)
        });

        Ok(())
    }

    pub fn get_input_status(&self) -> Result<bool, ()> {
        if self.periph.read().enable().bit_is_clear() {
            // " + ts((
                en: "Must be enabled to get status",
                de: "Muss aktiviert sein, um den Status abzurufen.",
                ja: "状態を取得するには、有効化されてなければなりません",
                zh: "获取状态必须被使能",
              )) + "
            return Err(());
        }

        if self.periph.read().direction().bit_is_set() {
            // " + ts((
                en: "Direction must be input",
                de: "Die Richtung muss input sein.",
                ja: "方向は入力でなければなりません",
                zh: "方向必须是输入",
              )) + "
            return Err(());
        }

        Ok(self.periph.read().input_status().bit_is_set())
    }
}
")

#tr((
en: [
  Because we need to enforce the restrictions on the hardware, we end up
  doing a lot of runtime checking which wastes time and resources, and
  this code will be much less pleasant for the developer to use.
],
de: [
  Da wir die Hardware-Beschränkungen durchsetzen müssen, führen wir
  letztlich zahlreiche Laufzeitüberprüfungen durch -- was Zeit und
  Ressourcen verschwendet --, und der Code ist für Entwickler deutlich
  weniger angenehm zu handhaben.
],
ja: [
  ハードウェアの制約を強制する必要があるため、時間とリソースを浪費する多くの実行時チェックを行うこととなり、開発者にとってこのコードは好ましくないです。
],
zh: [
  因为需要强制遵守硬件上的限制，所以最后做了很多运行时检查，它浪费了我们很多时间和资源，对于开发者来说，这个代码用起来就没那么愉快了。
]))

= #tr((
  en: [Type States],
  de: [Typzustände],
  ja: [型状態],
  zh: [类型状态(Type states)],
))

#tr((
en: [
  But what if instead, we used Rust's type system to enforce the state
  transition rules? Take this example:
],
de: [
  Was aber, wenn wir stattdessen das Typsystem von Rust nutzen würden, um
  die Regeln für Zustandsübergänge durchzusetzen? Betrachten wir dieses
  Beispiel:
],
ja: [
  しかし、代わりに、状態遷移の規則を強制するために、Rustの型システムを使うとどうなるでしょうか？この例を見て下さい。
],
zh: [
  但是，如果我们让Rust的类型系统去强制遵守状态转换的规则会怎样？看下这个例子:
]))

#raw(block: true, lang: "rust",
"/// " + ts((
    en: "GPIO interface",
    de: "GPIO-Schnittstelle",
    ja: "GPIOインタフェース",
    zh: "GPIO接口",
  )) + "
struct GpioConfig<ENABLED, DIRECTION, MODE> {
    /// " + ts((
        en: "GPIO Configuration structure generated by svd2rust",
        de: "Von svd2rust generierte GPIO-Konfigurationsstruktur",
        ja: "svd2rustによって生成されたGPIO設定構造体",
        zh: "由svd2rust产生的GPIO配置结构体",
      )) + "
    periph: GPIO_CONFIG,
    enabled: ENABLED,
    direction: DIRECTION,
    mode: MODE,
}

// " + ts((
    en: "Type states for MODE in GpioConfig",
    de: "Typzustaende fuer MODE in GpioConfig",
    ja: "GpioConfigのMODEのための型状態",
    zh: "GpioConfig中MODE的类型状态",
  )) + "
struct Disabled;
struct Enabled;
struct Output;
struct Input;
struct PulledLow;
struct PulledHigh;
struct HighZ;
struct DontCare;

/// " + ts((
    en: "These functions may be used on any GPIO Pin",
    de: "Diese Funktionen koennen an jedem GPIO-Pin verwendet werden.",
    ja: "これらの関数はどのGPIOピンにも使えます",
    zh: "这些函数可能被用于所有的GPIO管脚",
  )) + "
impl<EN, DIR, IN_MODE> GpioConfig<EN, DIR, IN_MODE> {
    pub fn into_disabled(self) -> GpioConfig<Disabled, DontCare, DontCare> {
        self.periph.modify(|_r, w| w.enable.disabled());
        GpioConfig {
            periph: self.periph,
            enabled: Disabled,
            direction: DontCare,
            mode: DontCare,
        }
    }

    pub fn into_enabled_input(self) -> GpioConfig<Enabled, Input, HighZ> {
        self.periph.modify(|_r, w| {
            w.enable.enabled()
             .direction.input()
             .input_mode.high_z()
        });
        GpioConfig {
            periph: self.periph,
            enabled: Enabled,
            direction: Input,
            mode: HighZ,
        }
    }

    pub fn into_enabled_output(self) -> GpioConfig<Enabled, Output, DontCare> {
        self.periph.modify(|_r, w| {
            w.enable.enabled()
             .direction.output()
             .input_mode.set_high()
        });
        GpioConfig {
            periph: self.periph,
            enabled: Enabled,
            direction: Output,
            mode: DontCare,
        }
    }
}

/// " + ts((
    en: "This function may be used on an Output Pin",
    de: "Diese Funktion kann fuer einen Ausgangspin verwendet werden.",
    ja: "この関数はOutputピンに使用できます",
    zh: "这个函数可能被用于一个输出管脚",
  )) + "
impl GpioConfig<Enabled, Output, DontCare> {
    pub fn set_bit(&mut self, set_high: bool) {
        self.periph.modify(|_r, w| w.output_mode.set_bit(set_high));
    }
}

/// " + ts((
    en: "These methods may be used on any enabled input GPIO",
    de: "Diese Methoden koennen auf jedem aktivierten Eingangs-GPIO verwendet werden.",
    ja: "これらのメソッドは、有効化された入力GPIOに使えます",
    zh: "这些方法可能被用于任意一个使能的输入GPIO",
  )) + "
impl<IN_MODE> GpioConfig<Enabled, Input, IN_MODE> {
    pub fn bit_is_set(&self) -> bool {
        self.periph.read().input_status.bit_is_set()
    }

    pub fn into_input_high_z(self) -> GpioConfig<Enabled, Input, HighZ> {
        self.periph.modify(|_r, w| w.input_mode().high_z());
        GpioConfig {
            periph: self.periph,
            enabled: Enabled,
            direction: Input,
            mode: HighZ,
        }
    }

    pub fn into_input_pull_down(self) -> GpioConfig<Enabled, Input, PulledLow> {
        self.periph.modify(|_r, w| w.input_mode().pull_low());
        GpioConfig {
            periph: self.periph,
            enabled: Enabled,
            direction: Input,
            mode: PulledLow,
        }
    }

    pub fn into_input_pull_up(self) -> GpioConfig<Enabled, Input, PulledHigh> {
        self.periph.modify(|_r, w| w.input_mode().pull_high());
        GpioConfig {
            periph: self.periph,
            enabled: Enabled,
            direction: Input,
            mode: PulledHigh,
        }
    }
}
")

#tr((
en: [
  Now let's see what the code using this would look like:
],
de: [
  Schauen wir uns nun an, wie der Code aussehen würde, der dies verwendet:
],
ja: [
  それでは、これを使うコードがどのようになるか、見てみましょう。
],
zh: [
  现在让我们看下代码如何用这个API:
]))

#raw(block: true, lang: "rust",
"/*
 * " + ts((
    en: "Example 1: Unconfigured to High-Z input",
    de: "Beispiel 1: Nicht konfiguriert als High-Z-Eingang",
    ja: "例1：未設定から高抵抗入力",
    zh: "案例 1: 从未配置到高阻输入",
  )) + "
 */
let pin: GpioConfig<Disabled, _, _> = get_gpio();

// " + ts((
    en: "Can't do this, pin isn't enabled!",
    de: "Das ist nicht moeglich, die PIN ist nicht aktiviert!",
    ja: "これはできません、ピンが有効になっていません！",
    zh: "不能这么做，pin没有被使能",
  )) + "
// pin.into_input_pull_down();

// " + ts((
    en: "Now turn the pin from unconfigured to a high-z input",
    de: "Schalten Sie den Pin nun von „unkonfiguriert“ auf einen hochohmigen Eingang 
  // (High-Z-Eingang) um.",
    ja: "今度は、未設定から高抵抗入力に変えます",
    zh: "现在把管脚从未配置变为高阻输入",
  )) + "
let input_pin = pin.into_enabled_input();

// " + ts((
    en: "Read from the pin",
    de: "Vom Pin lesen",
    ja: "ピンから値を読みます",
    zh: "从管脚读取",
  )) + "
let pin_state = input_pin.bit_is_set();

// " + ts((
    en: "Can't do this, input pins don't have this interface!",
    de: "Das ist nicht moeglich; Eingangs-Pins verfuegen nicht über diese 
  // Schnittstelle!",
    ja: "これはできません、入力ピンはこのインタフェースを持っていません！",
    zh: "不能这么做，输入管脚没有这个接口",
  )) + "
// input_pin.set_bit(true);

/*
 * " + ts((
    en: "Example 2: High-Z input to Pulled Low input",
    de: "Beispiel 2: Hochohmiger Eingang (High-Z) an auf Low-Pegel gezogenen Eingang",
    ja: "例2：高抵抗入力からプルダウン入力",
    zh: "案例 2: 高阻输入到下拉输入",
  )) + "
 */
let pulled_low = input_pin.into_input_pull_down();
let pin_state = pulled_low.bit_is_set();

/*
 * " + ts((
    en: "Example 3: Pulled Low input to Output, set high",
    de: "Beispiel 3: Eingang auf Low gezogen, Ausgang auf High gesetzt",
    ja: "例3：プルダウン入力から出力、ハイを設定",
    zh: "案例 3: 下拉输入到输出, 拉高",
  )) + "
 */
let output_pin = pulled_low.into_enabled_output();
output_pin.set_bit(true);

// " + ts((
    en: "Can't do this, output pins don't have this interface!",
    de: "Das geht nicht, Ausgangspins verfuegen nicht über diese Schnittstelle!",
    ja: "これはできません、出力ピンはこのインタフェースを持っていません！",
    zh: "不能这么做，输出管脚没有这个接口",
  )) + "
// output_pin.into_input_pull_down();
")

#tr((
en: [
  This is definitely a convenient way to store the state of the pin, but
  why do it this way? Why is this better than storing the state as an
  `enum` inside of our `GpioConfig` structure?
],
de: [
  Dies ist zweifellos eine praktische Möglichkeit, den Zustand des Pins zu
  speichern, aber warum sollte man es auf diese Weise tun? Warum ist das
  besser, als den Zustand als `enum` innerhalb unserer
  `GpioConfig`-Struktur zu speichern?
],
ja: [
  これは間違いなく、ピンの状態を保存するのに便利な方法ですが、なぜこのようにするのでしょうか？
  なぜ、`GpioConfig`構造体の中で、状態を`enum`として保存するより良い方法なのでしょうか？
],
zh: [
  这绝对是存储管脚状态的便捷方法，但是为什么这么做?为什么这比把状态当成一个`enum`存在我们的`GpioConfig`结构体中更好？
]))

= #tr((
  en: [Compile Time Functional Safety],
  de: [Funktionale Sicherheit zur Kompilierzeit],
  ja: [コンパイル時の機能の安全性],
  zh: [编译时功能安全(Functional Safety)],
))

#tr((
en: [
  Because we are enforcing our design constraints entirely at compile
  time, this incurs no runtime cost. It is impossible to set an output
  mode when you have a pin in an input mode. Instead, you must walk
  through the states by converting it to an output pin, and then setting
  the output mode. Because of this, there is no runtime penalty due to
  checking the current state before executing a function.
],
de: [
  Da wir unsere Designvorgaben vollständig zur Kompilierzeit durchsetzen,
  entstehen keinerlei Laufzeitkosten. Es ist unmöglich, einen Ausgabemodus
  einzustellen, solange sich ein Pin im Eingabemodus befindet. Stattdessen
  muss man die Zustände durchlaufen, indem man den Pin zunächst in einen
  Ausgangspin umwandelt und anschließend den Ausgabemodus festlegt.
  Dadurch entfällt der Laufzeitaufwand für die Überprüfung des aktuellen
  Zustands vor der Ausführung einer Funktion.
],
ja: [
  コンパイル時に、設計契約を完全に強制しているため、実行時コストはかかりません。入力方向のピンに対して、出力モードを設定することは不可能です。
  代わりに、そのピンを出力ピンに変換してから、出力モードを設定することで、状態を辿る必要があります。
  このおかげで、関数実行前に現在の状態をチェックすることによる実行時ペナルティは、ありません。
],
zh: [
  因为我们在编译时完全强制遵守设计约定，这造成了没有运行时开销。当管脚处于输入模式时时，是不可能设置输出模式的。必须先把它设置成一个输出管脚，然后再设置输出模式。因为在执行一个函数前会检查现在的状态，因此没有运行时消耗。
]))

#tr((
en: [
  Also, because these states are enforced by the type system, there is no
  longer room for errors by consumers of this interface. If they try to
  perform an illegal state transition, the code will not compile!
],
de: [
  Da diese Zustände zudem durch das Typsystem erzwungen werden, sind
  Fehler bei der Verwendung dieser Schnittstelle ausgeschlossen. Versucht
  der Nutzer einen unzulässigen Zustandsübergang, lässt sich der Code
  nicht kompilieren!
],
ja: [
  型システムによってこれらの状態が強制されるため、このインタフェースの利用者によるエラーの余地はもはや残っていません。
  もし利用者が不正な状態遷移をしようとすると、そのコードはコンパイルできません！
],
zh: [
  也因为这些状态被类型系统强制遵守，因此没有为这个接口的使用者留太多的犯错余地。如果它们尝试执行一个非法的状态转换，代码将不会编译成功！
]))
