name: CI

on:
  push: # Run CI for all branches except GitHub merge queue tmp branches
    branches-ignore:
    - "gh-readonly-queue/**"
  pull_request: # Run CI for PRs on any branch
  merge_group: # Run CI for the GitHub merge queue

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Python dependencies
        run: |
          pip3 install --user python-dateutil linkchecker
      - name: Put pip binary directory into path
        run: echo "~/.local/bin" >> $GITHUB_PATH

      - uses: moonrepo/setup-rust@v0
        with:
          bins: mdbook, mdbook-i18n-helpers

      - name: Build book
        run: mdbook build
      - name: Test book
        run: mdbook test
      - name: Check links
        run: linkchecker book

      - name: Build translations
        # Expand the list of langauges in the for loop as needed.
        # Update the language picker in theme/index.hbs when a
        # language is complete enough to be found by users.
        run: |
          for po_lang in da; do
              echo "::group::Building $po_lang translation"
              MDBOOK_BOOK__LANGUAGE=$po_lang \
              MDBOOK_OUTPUT__HTML__SITE_URL=/book/$po_lang/ \
              mdbook build -d book/$po_lang
              echo "::endgroup::"
          done

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: book

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        id: deployment
        uses: actions/deploy-pages@v1
